let data = [{
    "crop": "Ancient Fruit",
    "season": "All",
    "type": "Fruit",
    "regrows": true,
    "walkable": true,
    "growTime": 28,
    "regrowTime": 8,
    "yields": 1,
    "maxHarvests": 4,
    "sellPrice": 550,
    "seedCost": 0
  },
  {
    "crop": "Corn",
    "season": "Multi",
    "type": "Vegetable",
    "regrows": true,
    "walkable": true,
    "growTime": 14,
    "regrowTime": 4,
    "yields": 1,
    "maxHarvests": 11,
    "sellPrice": 50,
    "seedCost": 150
  },
  {
    "crop": "Coffee Beans",
    "season": "Multi",
    "type": "Other",
    "regrows": true,
    "walkable": true,
    "growTime": 10,
    "regrowTime": 2,
    "yields": 4,
    "maxHarvests": 23,
    "sellPrice": 15,
    "seedCost": 0
  },
  {
    "crop": "Rice",
    "season": "Spring",
    "type": "Vegetable",
    "growTime": 6,
    "yields": 1.1,
    "maxHarvests": 4,
    "sellPrice": 30,
    "seedCost": 0,
    "best": "Jar"
  },
  {
    "crop": "Parsnip",
    "season": "Spring",
    "type": "Vegetable",
    "regrows": false,
    "walkable": true,
    "growTime": 4,
    "yields": 1,
    "maxHarvests": 6,
    "sellPrice": 35,
    "seedCost": 20,
    "best": "Jar"
  },
  {
    "crop": "Garlic",
    "season": "Spring",
    "type": "Vegetable",
    "regrows": false,
    "walkable": true,
    "growTime": 4,
    "yields": 1,
    "maxHarvests": 6,
    "sellPrice": 60,
    "seedCost": 40,
    "best": "Jar"
  },
  {
    "crop": "Potato",
    "season": "Spring",
    "type": "Vegetable",
    "regrows": false,
    "walkable": true,
    "growTime": 6,
    "yields": 1.2,
    "maxHarvests": 4,
    "sellPrice": 80,
    "seedCost": 50,
    "best": "Jar"
  },
  {
    "crop": "Tulip",
    "season": "Spring",
    "type": "Flower",
    "regrows": false,
    "walkable": true,
    "growTime": 6,
    "yields": 1,
    "maxHarvests": 4,
    "sellPrice": 30,
    "seedCost": 20
  },
  {
    "crop": "Kale",
    "season": "Spring",
    "type": "Vegetable",
    "regrows": false,
    "walkable": true,
    "growTime": 6,
    "yields": 1,
    "maxHarvests": 4,
    "sellPrice": 110,
    "seedCost": 70,
    "best": "Jar"
  },
  {
    "crop": "Blue Jazz",
    "season": "Spring",
    "type": "Flower",
    "regrows": false,
    "walkable": true,
    "growTime": 7,
    "yields": 1,
    "maxHarvests": 3,
    "sellPrice": 50,
    "seedCost": 30
  },
  {
    "crop": "Strawberry",
    "season": "Spring",
    "type": "Fruit",
    "regrows": true,
    "walkable": true,
    "growTime": 8,
    "regrowTime": 4,
    "yields": 1,
    "maxHarvests": 5,
    "sellPrice": 120,
    "seedCost": 100,
    "best": "Keg"
  },
  {
    "crop": "Green Bean",
    "season": "Spring",
    "type": "Vegetable",
    "regrows": true,
    "walkable": false,
    "growTime": 10,
    "regrowTime": 3,
    "yields": 1,
    "maxHarvests": 6,
    "sellPrice": 40,
    "seedCost": 60,
    "best": "Jar"
  },
  {
    "crop": "Cauliflower",
    "season": "Spring",
    "type": "Vegetable",
    "regrows": false,
    "walkable": true,
    "growTime": 12,
    "yields": 1,
    "maxHarvests": 2,
    "sellPrice": 175,
    "seedCost": 80,
    "best": "Jar"
  },
  {
    "crop": "Rhubarb",
    "season": "Spring",
    "type": "Fruit",
    "regrows": false,
    "walkable": true,
    "growTime": 13,
    "yields": 1,
    "maxHarvests": 2,
    "sellPrice": 220,
    "seedCost": 100,
    "best": "Keg"
  },
  {
    "crop": "Wheat",
    "season": "Summer",
    "type": "Vegetable",
    "regrows": false,
    "walkable": true,
    "growTime": 4,
    "yields": 1,
    "maxHarvests": 6,
    "sellPrice": 25,
    "seedCost": 10,
    "best": "Keg"
  },
  {
    "crop": "Hot Pepper",
    "season": "Summer",
    "type": "Fruit",
    "regrows": true,
    "walkable": true,
    "growTime": 5,
    "regrowTime": 3,
    "yields": 1,
    "maxHarvests": 8,
    "sellPrice": 40,
    "seedCost": 40,
    "best": "Jar"
  },
  {
    "crop": "Radish",
    "season": "Summer",
    "type": "Vegetable",
    "regrows": false,
    "walkable": true,
    "growTime": 6,
    "yields": 1,
    "maxHarvests": 4,
    "sellPrice": 90,
    "seedCost": 40,
    "best": "Jar"
  },
  {
    "crop": "Poppy",
    "season": "Summer",
    "type": "Flower",
    "regrows": false,
    "walkable": true,
    "growTime": 7,
    "yields": 1,
    "maxHarvests": 3,
    "sellPrice": 140,
    "seedCost": 100
  },
  {
    "crop": "Summer Spangle",
    "season": "Summer",
    "type": "Flower",
    "regrows": false,
    "walkable": true,
    "growTime": 8,
    "yields": 1,
    "maxHarvests": 3,
    "sellPrice": 90,
    "seedCost": 50
  },
  {
    "crop": "Red Cabbage",
    "season": "Summer",
    "type": "Vegetable",
    "regrows": false,
    "walkable": true,
    "growTime": 9,
    "yields": 1,
    "maxHarvests": 3,
    "sellPrice": 260,
    "seedCost": 100,
    "best": "Keg"
  },
  {
    "crop": "Hops",
    "season": "Summer",
    "type": "Vegetable",
    "regrows": true,
    "walkable": false,
    "growTime": 11,
    "regrowTime": 1,
    "yields": 1,
    "maxHarvests": 17,
    "sellPrice": 25,
    "seedCost": 60,
    "best": "Keg"
  },
  {
    "crop": "Tomato",
    "season": "Summer",
    "type": "Vegetable",
    "regrows": true,
    "walkable": true,
    "growTime": 11,
    "regrowTime": 4,
    "yields": 1,
    "maxHarvests": 5,
    "sellPrice": 60,
    "seedCost": 50,
    "best": "Jar"
  },
  {
    "crop": "Melon",
    "season": "Summer",
    "type": "Fruit",
    "regrows": false,
    "walkable": true,
    "growTime": 12,
    "yields": 1,
    "maxHarvests": 2,
    "sellPrice": 250,
    "seedCost": 80,
    "best": "Keg"
  },
  {
    "crop": "Blueberry",
    "season": "Summer",
    "type": "Fruit",
    "regrows": true,
    "walkable": true,
    "growTime": 13,
    "regrowTime": 4,
    "yields": 3,
    "maxHarvests": 4,
    "sellPrice": 50,
    "seedCost": 80,
    "best": "Keg"
  },
  {
    "crop": "Starfruit",
    "season": "Summer",
    "type": "Fruit",
    "regrows": false,
    "walkable": true,
    "growTime": 13,
    "yields": 1,
    "maxHarvests": 2,
    "sellPrice": 750,
    "seedCost": 400,
    "best": "Keg"
  },
  {
    "crop": "Bok Choy",
    "season": "Fall",
    "type": "Vegetable",
    "regrows": false,
    "walkable": true,
    "growTime": 4,
    "yields": 1,
    "maxHarvests": 6,
    "sellPrice": 80,
    "seedCost": 50,
    "best": "Jar"
  },
  {
    "crop": "Eggplant",
    "season": "Fall",
    "type": "Vegetable",
    "regrows": true,
    "walkable": true,
    "growTime": 5,
    "regrowTime": 5,
    "yields": 1,
    "maxHarvests": 5,
    "sellPrice": 60,
    "seedCost": 20,
    "best": "Jar"
  },
  {
    "crop": "Beet",
    "season": "Fall",
    "type": "Vegetable",
    "regrows": false,
    "walkable": true,
    "growTime": 6,
    "yields": 1,
    "maxHarvests": 4,
    "sellPrice": 100,
    "seedCost": 20,
    "best": "Jar"
  },
  {
    "crop": "Cranberry",
    "season": "Fall",
    "type": "Fruit",
    "regrows": true,
    "walkable": true,
    "growTime": 7,
    "regrowTime": 5,
    "yields": 2,
    "maxHarvests": 5,
    "sellPrice": 75,
    "seedCost": 240,
    "best": "Keg"
  },
  {
    "crop": "Amaranth",
    "season": "Fall",
    "type": "Vegetable",
    "regrows": false,
    "walkable": true,
    "growTime": 7,
    "yields": 1,
    "maxHarvests": 3,
    "sellPrice": 150,
    "seedCost": 70,
    "best": "Jar"
  },
  {
    "crop": "Sunflower",
    "season": "Fall",
    "type": "Flower",
    "regrows": false,
    "walkable": true,
    "growTime": 8,
    "yields": 1,
    "maxHarvests": 3,
    "sellPrice": 80,
    "seedCost": 200
  },
  {
    "crop": "Artichoke",
    "season": "Fall",
    "type": "Vegetable",
    "regrows": false,
    "walkable": true,
    "growTime": 8,
    "yields": 1,
    "maxHarvests": 3,
    "sellPrice": 160,
    "seedCost": 30,
    "best": "Jar"
  },
  {
    "crop": "Yam",
    "season": "Fall",
    "type": "Vegetable",
    "regrows": false,
    "walkable": true,
    "growTime": 10,
    "yields": 1,
    "maxHarvests": 2,
    "sellPrice": 160,
    "seedCost": 60,
    "best": "Jar"
  },
  {
    "crop": "Grape",
    "season": "Fall",
    "type": "Fruit",
    "regrows": true,
    "walkable": false,
    "growTime": 10,
    "regrowTime": 3,
    "yields": 1,
    "maxHarvests": 6,
    "sellPrice": 80,
    "seedCost": 60,
    "best": "Keg"
  },
  {
    "crop": "Fairy Rose",
    "season": "Fall",
    "type": "Flower",
    "regrows": false,
    "walkable": true,
    "growTime": 12,
    "yields": 1,
    "maxHarvests": 2,
    "sellPrice": 290,
    "seedCost": 200,
    "best": "Keg"
  },
  {
    "crop": "Pumpkin",
    "season": "Fall",
    "type": "Vegetable",
    "regrows": false,
    "walkable": true,
    "growTime": 13,
    "yields": 1,
    "maxHarvests": 2,
    "sellPrice": 320,
    "seedCost": 100,
    "best": "Keg"
  },
  {
    "crop": "Sweet Gem Berry",
    "season": "Fall",
    "regrows": false,
    "walkable": true,
    "growTime": 24,
    "yields": 1,
    "maxHarvests": 1,
    "sellPrice": 3000,
    "seedCost": 1000,
    "best": "Keg"
  }
]

export default data;